In [1]:
import numpy as np

In [2]:
x = [1,2,3,4,5]


In [3]:
type(x)

list

In [4]:
arr = np.array(x)

In [5]:
type(arr)

numpy.ndarray

In [6]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [9]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.random.seed(50)
arr1 = np.random.randint(1,100,50)

In [11]:
arr1

array([49, 97, 12, 34, 95,  5, 71, 71, 23,  6,  3, 96, 72, 69, 79, 36, 93,
       92, 27, 91,  7, 21, 44, 32, 50, 86, 42, 65,  7, 20,  3, 80, 31, 36,
       27, 61, 67, 77, 97, 68,  3, 11, 52,  1, 94, 94, 95,  1, 12, 31])

In [12]:
np.random.seed(50)
arr2 = np.random.randint(10,1000,50)
arr2

array([698, 490, 917, 119, 299, 142,  80, 239,  80, 288, 759, 143, 268,
       105, 260,  81, 377, 462, 984, 173, 870, 613, 164, 228, 144, 414,
       821, 809, 571, 351, 116, 947, 330, 517, 528, 157, 652,  89, 424,
       115, 429, 509,  36, 582, 381, 844, 982, 845, 140, 788])

In [13]:
arr1.reshape(10,5)

array([[49, 97, 12, 34, 95],
       [ 5, 71, 71, 23,  6],
       [ 3, 96, 72, 69, 79],
       [36, 93, 92, 27, 91],
       [ 7, 21, 44, 32, 50],
       [86, 42, 65,  7, 20],
       [ 3, 80, 31, 36, 27],
       [61, 67, 77, 97, 68],
       [ 3, 11, 52,  1, 94],
       [94, 95,  1, 12, 31]])

In [14]:
arr2.reshape(5,10)

array([[698, 490, 917, 119, 299, 142,  80, 239,  80, 288],
       [759, 143, 268, 105, 260,  81, 377, 462, 984, 173],
       [870, 613, 164, 228, 144, 414, 821, 809, 571, 351],
       [116, 947, 330, 517, 528, 157, 652,  89, 424, 115],
       [429, 509,  36, 582, 381, 844, 982, 845, 140, 788]])

In [15]:
arr3 = np.random.randint(0,1000,50).reshape(10,5)

In [16]:
arr3

array([[622, 947,   0,  93, 221],
       [606,   0, 139, 926, 666],
       [583,  51, 156, 152,  91],
       [174,  62, 909, 711, 548],
       [740, 128, 186, 811, 704],
       [403, 826,  45, 211, 385],
       [701, 777, 797, 308, 427],
       [101, 343, 288, 787, 559],
       [509, 197,  92, 774, 833],
       [164, 340,  36, 300, 309]])

In [17]:
arr1.max()

97

In [18]:
arr1.min()

1

In [19]:
arr1.mean()

48.72

In [20]:
arr1.argmin()

43

In [21]:
arr1.argmax()

1

In [22]:
arr1.shape

(50,)

In [23]:
arr3.shape

(10, 5)

In [24]:
arr3[2,:]

array([583,  51, 156, 152,  91])

In [25]:
arr3[:,4]

array([221, 666,  91, 548, 704, 385, 427, 559, 833, 309])

In [26]:
arr3[0:5,0:5]

array([[622, 947,   0,  93, 221],
       [606,   0, 139, 926, 666],
       [583,  51, 156, 152,  91],
       [174,  62, 909, 711, 548],
       [740, 128, 186, 811, 704]])

In [27]:
arr3[0:5,0:5]=1
arr3

array([[  1,   1,   1,   1,   1],
       [  1,   1,   1,   1,   1],
       [  1,   1,   1,   1,   1],
       [  1,   1,   1,   1,   1],
       [  1,   1,   1,   1,   1],
       [403, 826,  45, 211, 385],
       [701, 777, 797, 308, 427],
       [101, 343, 288, 787, 559],
       [509, 197,  92, 774, 833],
       [164, 340,  36, 300, 309]])

In [28]:
arr5 = arr3.copy()
arr5

array([[  1,   1,   1,   1,   1],
       [  1,   1,   1,   1,   1],
       [  1,   1,   1,   1,   1],
       [  1,   1,   1,   1,   1],
       [  1,   1,   1,   1,   1],
       [403, 826,  45, 211, 385],
       [701, 777, 797, 308, 427],
       [101, 343, 288, 787, 559],
       [509, 197,  92, 774, 833],
       [164, 340,  36, 300, 309]])